// Generated by lsc from engine.ts

type Board = seq<int>

const N: int := 4

const SIZE: int := 16

const EMPTY: int := 0

const LEFT: int := 0

const RIGHT: int := 1

const DOWN: int := 3

method slideLine(line: seq<int>) returns (res: seq<int>)
  ensures (|res| == |line|)
  ensures (sumTo(res, |res|) == sumTo(line, |line|))
  ensures ((2 * nzTo(res, |res|)) >= nzTo(line, |line|))
  ensures (nzTo(res, |res|) <= nzTo(line, |line|))
  ensures forall p: int, q: int :: ((0 <= p) ==> (p < q) ==> (q < |res|) ==> (res[p] == EMPTY) ==> (res[q] == EMPTY))
{
  var tiles: seq<int> := [];
  var i := 0;
  while (i < |line|)
    invariant (0 <= i)
    invariant (i <= |line|)
    invariant (|tiles| <= i)
    invariant (sumTo(tiles, |tiles|) == sumTo(line, i))
    invariant (nzTo(line, i) == |tiles|)
    invariant forall k: int :: ((0 <= k) ==> (k < |tiles|) ==> (tiles[k] != EMPTY))
  {
    if (line[i] != EMPTY) {
      tiles := (tiles + [line[i]]);
    }
    i := (i + 1);
  }
  var out: seq<int> := [];
  var j := 0;
  while (j < |tiles|)
    invariant (0 <= j)
    invariant (j <= |tiles|)
    invariant (|out| <= j)
    invariant ((2 * |out|) >= j)
    invariant (sumTo(out, |out|) == sumTo(tiles, j))
    invariant (nzTo(out, |out|) == |out|)
    invariant forall k: int :: ((0 <= k) ==> (k < |out|) ==> (out[k] != EMPTY))
    invariant forall k: int :: ((0 <= k) ==> (k < |tiles|) ==> (tiles[k] != EMPTY))
    decreases (|tiles| - j)
  {
    if (((j + 1) < |tiles|) && (tiles[j] == tiles[(j + 1)])) {
      out := (out + [(tiles[j] + tiles[(j + 1)])]);
      j := (j + 2);
    } else {
      out := (out + [tiles[j]]);
      j := (j + 1);
    }
  }
  while (|out| < |line|)
    invariant (|out| <= |line|)
    invariant (sumTo(out, |out|) == sumTo(line, |line|))
    invariant ((2 * nzTo(out, |out|)) >= nzTo(line, |line|))
    invariant (nzTo(out, |out|) <= nzTo(line, |line|))
    decreases (|line| - |out|)
  {
    out := (out + [EMPTY]);
  }
  return out;
}

method getRow(b: seq<int>, r: int) returns (res: seq<int>)
  requires (|b| == SIZE)
  requires (0 <= r)
  requires (r < N)
  ensures (|res| == N)
  ensures (sumTo(res, |res|) == (sumTo(b, ((r * N) + N)) - sumTo(b, (r * N))))
{
  var out: seq<int> := [];
  var c := 0;
  while (c < N)
    invariant (0 <= c)
    invariant (c <= N)
    invariant (|out| == c)
    invariant (sumTo(out, |out|) == (sumTo(b, ((r * N) + c)) - sumTo(b, (r * N))))
  {
    out := (out + [b[((r * N) + c)]]);
    c := (c + 1);
  }
  return out;
}

method getCol(b: seq<int>, c: int) returns (res: seq<int>)
  requires (|b| == SIZE)
  requires (0 <= c)
  requires (c < N)
  ensures (|res| == N)
  ensures (sumTo(res, |res|) == colSumTo(b, c, N))
{
  var out: seq<int> := [];
  var r := 0;
  while (r < N)
    invariant (0 <= r)
    invariant (r <= N)
    invariant (|out| == r)
    invariant (sumTo(out, |out|) == colSumTo(b, c, r))
  {
    out := (out + [b[((r * N) + c)]]);
    r := (r + 1);
  }
  return out;
}

method reversed(a: seq<int>) returns (res: seq<int>)
  ensures (|res| == |a|)
  ensures (sumTo(res, |res|) == sumTo(a, |a|))
{
  var out: seq<int> := [];
  var i := (|a| - 1);
  while (i >= 0)
    invariant (-1 <= i)
    invariant (i < |a|)
    invariant (|out| == ((|a| - 1) - i))
    invariant (sumTo(out, |out|) == (sumTo(a, |a|) - sumTo(a, (i + 1))))
  {
    out := (out + [a[i]]);
    i := (i - 1);
  }
  return out;
}

method applyMove(b: seq<int>, dir: int) returns (res: seq<int>)
  requires (|b| == SIZE)
  ensures (|res| == |b|)
  ensures (sumTo(res, |res|) == sumTo(b, |b|))
{
  var out := b;
  if ((dir == LEFT) || (dir == RIGHT)) {
    var r := 0;
    while (r < N)
      invariant (0 <= r)
      invariant (r <= N)
      invariant (|out| == |b|)
      invariant (sumTo(out, (r * N)) == sumTo(b, (r * N)))
      invariant forall k: int :: (((r * N) <= k) ==> (k < SIZE) ==> (out[k] == b[k]))
    {
      var i_t0 := getRow(b, r);
      var line := i_t0;
      if (dir == RIGHT) {
        line := reversed(line);
      }
      var i_t1 := slideLine(line);
      var s := i_t1;
      if (dir == RIGHT) {
        s := reversed(s);
      }
      var c := 0;
      while (c < N)
        invariant (0 <= c)
        invariant (c <= N)
        invariant (|out| == |b|)
        invariant (|s| == N)
        invariant (sumTo(s, |s|) == (sumTo(b, ((r * N) + N)) - sumTo(b, (r * N))))
        invariant (sumTo(out, (r * N)) == sumTo(b, (r * N)))
        invariant (sumTo(out, ((r * N) + c)) == (sumTo(b, (r * N)) + sumTo(s, c)))
        invariant forall k: int :: ((((r * N) + c) <= k) ==> (k < SIZE) ==> (out[k] == b[k]))
      {
        out := out[((r * N) + c) := s[c]];
        c := (c + 1);
      }
      r := (r + 1);
    }
  } else {
    var c := 0;
    while (c < N)
      invariant (0 <= c)
      invariant (c <= N)
      invariant (|out| == |b|)
      invariant (sumTo(out, SIZE) == sumTo(b, SIZE))
      invariant forall cc: int, rr: int :: ((c <= cc) ==> (cc < N) ==> (0 <= rr) ==> (rr < N) ==> (cell(out, rr, cc) == cell(b, rr, cc)))
    {
      var i_t2 := getCol(b, c);
      var line := i_t2;
      if (dir == DOWN) {
        line := reversed(line);
      }
      var i_t3 := slideLine(line);
      var s := i_t3;
      if (dir == DOWN) {
        s := reversed(s);
      }
      var r := 0;
      while (r < N)
        invariant (0 <= r)
        invariant (r <= N)
        invariant (|out| == |b|)
        invariant (|s| == N)
        invariant (sumTo(s, |s|) == colSumTo(b, c, N))
        invariant (sumTo(out, SIZE) == ((sumTo(b, SIZE) + sumTo(s, r)) - colSumTo(b, c, r)))
        invariant forall rr: int :: ((r <= rr) ==> (rr < N) ==> (cell(out, rr, c) == cell(b, rr, c)))
        invariant forall cc: int, rr2: int :: (((c + 1) <= cc) ==> (cc < N) ==> (0 <= rr2) ==> (rr2 < N) ==> (cell(out, rr2, cc) == cell(b, rr2, cc)))
      {
        out := out[((r * N) + c) := s[r]];
        r := (r + 1);
      }
      c := (c + 1);
    }
  }
  return out;
}

method boardSum(b: seq<int>) returns (res: int)
  ensures (res == sumTo(b, |b|))
{
  var s := 0;
  var i := 0;
  while (i < |b|)
    invariant (0 <= i)
    invariant (i <= |b|)
    invariant (s == sumTo(b, i))
  {
    s := (s + b[i]);
    i := (i + 1);
  }
  return s;
}
