// Generated by lsc from engine.ts

const EMPTY: int := 0

// --- proof additions -------------------------------------------------------
// L2 conservation uses sumTo (prefix sum); L3 no-double-merge uses nzTo
// (prefix count of nonzeros). Each has a prefix-stability lemma and an
// append lemma — the workhorses that let us reason about the seq-building loops.

ghost function sumTo(s: seq<int>, n: int): int
  requires 0 <= n <= |s|
{
  if n == 0 then 0 else sumTo(s, n - 1) + s[n - 1]
}

lemma SumPrefix(s: seq<int>, x: int, n: int)
  requires 0 <= n <= |s|
  ensures sumTo(s + [x], n) == sumTo(s, n)
{
  if n == 0 { } else { SumPrefix(s, x, n - 1); }
}

lemma SumAppend(s: seq<int>, x: int)
  ensures sumTo(s + [x], |s| + 1) == sumTo(s, |s|) + x
{
  SumPrefix(s, x, |s|);
}

ghost function nzTo(s: seq<int>, n: int): int
  requires 0 <= n <= |s|
{
  if n == 0 then 0 else nzTo(s, n - 1) + (if s[n - 1] != 0 then 1 else 0)
}

lemma NzPrefix(s: seq<int>, x: int, n: int)
  requires 0 <= n <= |s|
  ensures nzTo(s + [x], n) == nzTo(s, n)
{
  if n == 0 { } else { NzPrefix(s, x, n - 1); }
}

lemma NzAppend(s: seq<int>, x: int)
  ensures nzTo(s + [x], |s| + 1) == nzTo(s, |s|) + (if x != 0 then 1 else 0)
{
  NzPrefix(s, x, |s|);
}
// ---------------------------------------------------------------------------

method slideLine(line: seq<int>) returns (res: seq<int>)
  ensures (|res| == |line|)
  ensures (sumTo(res, |res|) == sumTo(line, |line|))
  ensures ((2 * nzTo(res, |res|)) >= nzTo(line, |line|))
  ensures (nzTo(res, |res|) <= nzTo(line, |line|))
  ensures forall p: int, q: int :: ((0 <= p) ==> (p < q) ==> (q < |res|) ==> (res[p] == EMPTY) ==> (res[q] == EMPTY))
{
  var tiles: seq<int> := [];
  var i := 0;
  while (i < |line|)
    invariant (0 <= i)
    invariant (i <= |line|)
    invariant (|tiles| <= i)
    invariant (sumTo(tiles, |tiles|) == sumTo(line, i))
    invariant (nzTo(line, i) == |tiles|)
    invariant forall k: int :: ((0 <= k) ==> (k < |tiles|) ==> (tiles[k] != EMPTY))
  {
    if (line[i] != EMPTY) {
      SumAppend(tiles, line[i]);
      NzAppend(tiles, line[i]);
      tiles := (tiles + [line[i]]);
    }
    i := (i + 1);
  }
  var out: seq<int> := [];
  var j := 0;
  while (j < |tiles|)
    invariant (0 <= j)
    invariant (j <= |tiles|)
    invariant (|out| <= j)
    invariant ((2 * |out|) >= j)
    invariant (sumTo(out, |out|) == sumTo(tiles, j))
    invariant (nzTo(out, |out|) == |out|)
    invariant forall k: int :: ((0 <= k) ==> (k < |out|) ==> (out[k] != EMPTY))
    invariant forall k: int :: ((0 <= k) ==> (k < |tiles|) ==> (tiles[k] != EMPTY))
    decreases (|tiles| - j)
  {
    if (((j + 1) < |tiles|) && (tiles[j] == tiles[(j + 1)])) {
      SumAppend(out, (tiles[j] + tiles[(j + 1)]));
      NzAppend(out, (tiles[j] + tiles[(j + 1)]));
      out := (out + [(tiles[j] + tiles[(j + 1)])]);
      j := (j + 2);
    } else {
      SumAppend(out, tiles[j]);
      NzAppend(out, tiles[j]);
      out := (out + [tiles[j]]);
      j := (j + 1);
    }
  }
  ghost var M := |out|; // split point: [0,M) are tiles, [M,|line|) become empty
  while (|out| < |line|)
    invariant (|out| <= |line|)
    invariant (sumTo(out, |out|) == sumTo(line, |line|))
    invariant ((2 * nzTo(out, |out|)) >= nzTo(line, |line|))
    invariant (nzTo(out, |out|) <= nzTo(line, |line|))
    invariant (M <= |out|)
    invariant forall k: int :: ((0 <= k) ==> (k < M) ==> (out[k] != EMPTY))
    invariant forall k: int :: ((M <= k) ==> (k < |out|) ==> (out[k] == EMPTY))
    decreases (|line| - |out|)
  {
    SumAppend(out, EMPTY);
    NzAppend(out, EMPTY);
    out := (out + [EMPTY]);
  }
  return out;
}
