// Generated by lsc from engine.ts

type Board = seq<int>

const N: int := 4

const SIZE: int := 16

const EMPTY: int := 0

const LEFT: int := 0

const RIGHT: int := 1

const DOWN: int := 3

// --- proof additions -------------------------------------------------------
// L2 conservation uses sumTo (prefix sum); L3 no-double-merge uses nzTo
// (prefix count of nonzeros). colSumTo is the strided column analogue of sumTo,
// used to lift per-line conservation to the whole board.

ghost function sumTo(s: seq<int>, n: int): int
  requires 0 <= n <= |s|
{
  if n == 0 then 0 else sumTo(s, n - 1) + s[n - 1]
}

lemma SumPrefix(s: seq<int>, x: int, n: int)
  requires 0 <= n <= |s|
  ensures sumTo(s + [x], n) == sumTo(s, n)
{
  if n == 0 { } else { SumPrefix(s, x, n - 1); }
}

lemma SumAppend(s: seq<int>, x: int)
  ensures sumTo(s + [x], |s| + 1) == sumTo(s, |s|) + x
{
  SumPrefix(s, x, |s|);
}

ghost function nzTo(s: seq<int>, n: int): int
  requires 0 <= n <= |s|
{
  if n == 0 then 0 else nzTo(s, n - 1) + (if s[n - 1] != 0 then 1 else 0)
}

lemma NzPrefix(s: seq<int>, x: int, n: int)
  requires 0 <= n <= |s|
  ensures nzTo(s + [x], n) == nzTo(s, n)
{
  if n == 0 { } else { NzPrefix(s, x, n - 1); }
}

lemma NzAppend(s: seq<int>, x: int)
  ensures nzTo(s + [x], |s| + 1) == nzTo(s, |s|) + (if x != 0 then 1 else 0)
{
  NzPrefix(s, x, |s|);
}

// Sum of column c over the first n rows: b[0*N+c] + b[1*N+c] + ... + b[(n-1)*N+c].
ghost function colSumTo(b: seq<int>, c: int, n: int): int
  requires |b| == SIZE
  requires 0 <= c < N
  requires 0 <= n <= N
{
  if n == 0 then 0 else colSumTo(b, c, n - 1) + b[(n - 1) * N + c]
}

// Cell (r,c) of a board — a trigger-friendly wrapper for flat indexing, so the
// "untouched columns" quantifiers trigger on cell(...) instead of on `r*N+c`
// (Dafny won't pick a multiplication term as a trigger).
ghost function cell(b: seq<int>, r: int, c: int): int
  requires |b| == SIZE
  requires 0 <= r < N
  requires 0 <= c < N
{
  b[r * N + c]
}

// Updating index i leaves every prefix ending at or before i unchanged.
lemma SumUpdateBeyond(t: seq<int>, i: int, v: int, n: int)
  requires 0 <= n <= i < |t|
  ensures sumTo(t[i := v], n) == sumTo(t, n)
  decreases n
{
  if n == 0 { } else { SumUpdateBeyond(t, i, v, n - 1); }
}

// Updating index i shifts the whole sum by (v - t[i]).
lemma SumToUpdateUpTo(t: seq<int>, i: int, v: int, n: int)
  requires 0 <= i < n <= |t|
  ensures sumTo(t[i := v], n) == sumTo(t, n) - t[i] + v
  decreases n
{
  if n == i + 1 { SumUpdateBeyond(t, i, v, i); } else { SumToUpdateUpTo(t, i, v, n - 1); }
}

lemma SumToUpdate(t: seq<int>, i: int, v: int)
  requires 0 <= i < |t|
  ensures sumTo(t[i := v], |t|) == sumTo(t, |t|) - t[i] + v
{
  SumToUpdateUpTo(t, i, v, |t|);
}

// The flat index r*N+c is unique per (row, column) for columns in [0, N).
// This is what lets a single-cell write leave other columns undisturbed.
lemma IndexInjective(r1: int, c1: int, r2: int, c2: int)
  requires 0 <= c1 < N && 0 <= c2 < N && 0 <= r1 && 0 <= r2
  ensures (r1 * N + c1 == r2 * N + c2) ==> (r1 == r2 && c1 == c2)
{
}
// ---------------------------------------------------------------------------

method slideLine(line: seq<int>) returns (res: seq<int>)
  ensures (|res| == |line|)
  ensures (sumTo(res, |res|) == sumTo(line, |line|))
  ensures ((2 * nzTo(res, |res|)) >= nzTo(line, |line|))
  ensures (nzTo(res, |res|) <= nzTo(line, |line|))
  ensures forall p: int, q: int :: ((0 <= p) ==> (p < q) ==> (q < |res|) ==> (res[p] == EMPTY) ==> (res[q] == EMPTY))
{
  var tiles: seq<int> := [];
  var i := 0;
  while (i < |line|)
    invariant (0 <= i)
    invariant (i <= |line|)
    invariant (|tiles| <= i)
    invariant (sumTo(tiles, |tiles|) == sumTo(line, i))
    invariant (nzTo(line, i) == |tiles|)
    invariant forall k: int :: ((0 <= k) ==> (k < |tiles|) ==> (tiles[k] != EMPTY))
  {
    if (line[i] != EMPTY) {
      SumAppend(tiles, line[i]);
      NzAppend(tiles, line[i]);
      tiles := (tiles + [line[i]]);
    }
    i := (i + 1);
  }
  var out: seq<int> := [];
  var j := 0;
  while (j < |tiles|)
    invariant (0 <= j)
    invariant (j <= |tiles|)
    invariant (|out| <= j)
    invariant ((2 * |out|) >= j)
    invariant (sumTo(out, |out|) == sumTo(tiles, j))
    invariant (nzTo(out, |out|) == |out|)
    invariant forall k: int :: ((0 <= k) ==> (k < |out|) ==> (out[k] != EMPTY))
    invariant forall k: int :: ((0 <= k) ==> (k < |tiles|) ==> (tiles[k] != EMPTY))
    decreases (|tiles| - j)
  {
    if (((j + 1) < |tiles|) && (tiles[j] == tiles[(j + 1)])) {
      SumAppend(out, (tiles[j] + tiles[(j + 1)]));
      NzAppend(out, (tiles[j] + tiles[(j + 1)]));
      out := (out + [(tiles[j] + tiles[(j + 1)])]);
      j := (j + 2);
    } else {
      SumAppend(out, tiles[j]);
      NzAppend(out, tiles[j]);
      out := (out + [tiles[j]]);
      j := (j + 1);
    }
  }
  ghost var M := |out|; // split point: [0,M) are tiles, [M,|line|) become empty
  while (|out| < |line|)
    invariant (|out| <= |line|)
    invariant (sumTo(out, |out|) == sumTo(line, |line|))
    invariant ((2 * nzTo(out, |out|)) >= nzTo(line, |line|))
    invariant (nzTo(out, |out|) <= nzTo(line, |line|))
    invariant (M <= |out|)
    invariant forall k: int :: ((0 <= k) ==> (k < M) ==> (out[k] != EMPTY))
    invariant forall k: int :: ((M <= k) ==> (k < |out|) ==> (out[k] == EMPTY))
    decreases (|line| - |out|)
  {
    SumAppend(out, EMPTY);
    NzAppend(out, EMPTY);
    out := (out + [EMPTY]);
  }
  return out;
}

method getRow(b: seq<int>, r: int) returns (res: seq<int>)
  requires (|b| == SIZE)
  requires (0 <= r)
  requires (r < N)
  ensures (|res| == N)
  ensures (sumTo(res, |res|) == (sumTo(b, ((r * N) + N)) - sumTo(b, (r * N))))
{
  var out: seq<int> := [];
  var c := 0;
  while (c < N)
    invariant (0 <= c)
    invariant (c <= N)
    invariant (|out| == c)
    invariant (sumTo(out, |out|) == (sumTo(b, ((r * N) + c)) - sumTo(b, (r * N))))
  {
    SumAppend(out, b[((r * N) + c)]);
    out := (out + [b[((r * N) + c)]]);
    c := (c + 1);
  }
  return out;
}

method getCol(b: seq<int>, c: int) returns (res: seq<int>)
  requires (|b| == SIZE)
  requires (0 <= c)
  requires (c < N)
  ensures (|res| == N)
  ensures (sumTo(res, |res|) == colSumTo(b, c, N))
{
  var out: seq<int> := [];
  var r := 0;
  while (r < N)
    invariant (0 <= r)
    invariant (r <= N)
    invariant (|out| == r)
    invariant (sumTo(out, |out|) == colSumTo(b, c, r))
  {
    SumAppend(out, b[((r * N) + c)]);
    out := (out + [b[((r * N) + c)]]);
    r := (r + 1);
  }
  return out;
}

method reversed(a: seq<int>) returns (res: seq<int>)
  ensures (|res| == |a|)
  ensures (sumTo(res, |res|) == sumTo(a, |a|))
{
  var out: seq<int> := [];
  var i := (|a| - 1);
  while (i >= 0)
    invariant (-1 <= i)
    invariant (i < |a|)
    invariant (|out| == ((|a| - 1) - i))
    invariant (sumTo(out, |out|) == (sumTo(a, |a|) - sumTo(a, (i + 1))))
  {
    SumAppend(out, a[i]);
    out := (out + [a[i]]);
    i := (i - 1);
  }
  return out;
}

method applyMove(b: seq<int>, dir: int) returns (res: seq<int>)
  requires (|b| == SIZE)
  ensures (|res| == |b|)
  ensures (sumTo(res, |res|) == sumTo(b, |b|))
{
  var out := b;
  if ((dir == LEFT) || (dir == RIGHT)) {
    var r := 0;
    while (r < N)
      invariant (0 <= r)
      invariant (r <= N)
      invariant (|out| == |b|)
      invariant (sumTo(out, (r * N)) == sumTo(b, (r * N)))
      invariant forall k: int :: (((r * N) <= k) ==> (k < SIZE) ==> (out[k] == b[k]))
    {
      var i_t0 := getRow(b, r);
      var line := i_t0;
      if (dir == RIGHT) {
        line := reversed(line);
      }
      var i_t1 := slideLine(line);
      var s := i_t1;
      if (dir == RIGHT) {
        s := reversed(s);
      }
      var c := 0;
      while (c < N)
        invariant (0 <= c)
        invariant (c <= N)
        invariant (|out| == |b|)
        invariant (|s| == N)
        invariant (sumTo(s, |s|) == (sumTo(b, ((r * N) + N)) - sumTo(b, (r * N))))
        invariant (sumTo(out, (r * N)) == sumTo(b, (r * N)))
        invariant (sumTo(out, ((r * N) + c)) == (sumTo(b, (r * N)) + sumTo(s, c)))
        invariant forall k: int :: ((((r * N) + c) <= k) ==> (k < SIZE) ==> (out[k] == b[k]))
      {
        SumUpdateBeyond(out, ((r * N) + c), s[c], (r * N));
        SumUpdateBeyond(out, ((r * N) + c), s[c], ((r * N) + c));
        assert sumTo(s, c + 1) == sumTo(s, c) + s[c];
        out := out[((r * N) + c) := s[c]];
        c := (c + 1);
      }
      r := (r + 1);
    }
  } else {
    var c := 0;
    while (c < N)
      invariant (0 <= c)
      invariant (c <= N)
      invariant (|out| == |b|)
      invariant (sumTo(out, SIZE) == sumTo(b, SIZE))
      invariant forall cc: int, rr: int :: ((c <= cc) ==> (cc < N) ==> (0 <= rr) ==> (rr < N) ==> (cell(out, rr, cc) == cell(b, rr, cc)))
    {
      var i_t2 := getCol(b, c);
      var line := i_t2;
      if (dir == DOWN) {
        line := reversed(line);
      }
      var i_t3 := slideLine(line);
      var s := i_t3;
      if (dir == DOWN) {
        s := reversed(s);
      }
      var r := 0;
      while (r < N)
        invariant (0 <= r)
        invariant (r <= N)
        invariant (|out| == |b|)
        invariant (|s| == N)
        invariant (sumTo(s, |s|) == colSumTo(b, c, N))
        invariant (sumTo(out, SIZE) == ((sumTo(b, SIZE) + sumTo(s, r)) - colSumTo(b, c, r)))
        invariant forall rr: int :: ((r <= rr) ==> (rr < N) ==> (cell(out, rr, c) == cell(b, rr, c)))
        invariant forall cc: int, rr2: int :: (((c + 1) <= cc) ==> (cc < N) ==> (0 <= rr2) ==> (rr2 < N) ==> (cell(out, rr2, cc) == cell(b, rr2, cc)))
      {
        assert cell(out, r, c) == cell(b, r, c);
        assert out[((r * N) + c)] == b[((r * N) + c)];
        SumToUpdate(out, ((r * N) + c), s[r]);
        assert sumTo(s, r + 1) == sumTo(s, r) + s[r];
        assert colSumTo(b, c, r + 1) == colSumTo(b, c, r) + b[((r * N) + c)];
        // Columns > c stay untouched: writing index r*N+c can't land in any other
        // column (IndexInjective), so every other cell keeps its value.
        forall cc2: int, rr3: int | ((c + 1) <= cc2) && (cc2 < N) && (0 <= rr3) && (rr3 < N)
          ensures cell(out[((r * N) + c) := s[r]], rr3, cc2) == cell(b, rr3, cc2)
        {
          IndexInjective(rr3, cc2, r, c);
          assert cell(out, rr3, cc2) == cell(b, rr3, cc2);
        }
        // Column c, rows > r stay untouched (their flat index strictly exceeds r*N+c).
        forall rr4: int | ((r + 1) <= rr4) && (rr4 < N)
          ensures cell(out[((r * N) + c) := s[r]], rr4, c) == cell(b, rr4, c)
        {
          assert cell(out, rr4, c) == cell(b, rr4, c);
        }
        out := out[((r * N) + c) := s[r]];
        r := (r + 1);
      }
      c := (c + 1);
    }
  }
  return out;
}

method boardSum(b: seq<int>) returns (res: int)
  ensures (res == sumTo(b, |b|))
{
  var s := 0;
  var i := 0;
  while (i < |b|)
    invariant (0 <= i)
    invariant (i <= |b|)
    invariant (s == sumTo(b, i))
  {
    s := (s + b[i]);
    i := (i + 1);
  }
  return s;
}
