// Generated by lsc from replay_core.ts

function statesFrom<S(==), A(==)>(step: (S, A) -> S, s: S, actions: seq<A>): seq<S>
  decreases |actions|
{
  if (|actions| == 0) then
    [s]
  else
    var rest := statesFrom(step, step(s, actions[0]), actions[1..]);
    ([s] + rest)
}

lemma statesFrom_ensures<S, A>(step: (S, A) -> S, s: S, actions: seq<A>)
  ensures (|statesFrom(step, s, actions)| == (|actions| + 1))
  ensures (statesFrom(step, s, actions)[0] == s)
  ensures forall i: int :: ((0 <= i) ==> (i < |actions|) ==> (statesFrom(step, s, actions)[(i + 1)] == step(statesFrom(step, s, actions)[i], actions[i])))
  decreases |actions|
{
  // --- proof addition: induction on the action log -------------------------
  if (|actions| == 0) {
  } else {
    var rest := statesFrom(step, step(s, actions[0]), actions[1..]);
    statesFrom_ensures(step, step(s, actions[0]), actions[1..]); // IH on the tail
    assert statesFrom(step, s, actions) == [s] + rest;
    forall i | 0 <= i < |actions|
      ensures ([s] + rest)[i + 1] == step(([s] + rest)[i], actions[i])
    {
      if (i == 0) {
        // ([s]+rest)[1] == rest[0] == step(s, actions[0]) == step(([s]+rest)[0], actions[0])
      } else {
        assert ([s] + rest)[i + 1] == rest[i];
        assert ([s] + rest)[i] == rest[i - 1];
        assert actions[1..][i - 1] == actions[i];
      }
    }
  }
}

function validateFrom<S(==), A(==)>(step: (S, A) -> S, legal: (S, A) -> bool, s: S, befores: seq<S>, actions: seq<A>): bool
  requires (|befores| == |actions|)
  decreases |actions|
{
  ((|actions| == 0) || (if (befores[0] != s) then false else (if !(legal(s, actions[0])) then false else validateFrom(step, legal, step(s, actions[0]), befores[1..], actions[1..]))))
}

lemma validateFrom_ensures<S, A>(step: (S, A) -> S, legal: (S, A) -> bool, s: S, befores: seq<S>, actions: seq<A>)
  requires (|befores| == |actions|)
  ensures ((validateFrom(step, legal, s, befores, actions) == true) ==> (|actions| > 0) ==> (befores[0] == s))
  ensures ((validateFrom(step, legal, s, befores, actions) == true) ==> forall i: int :: ((0 <= i) ==> ((i + 1) < |actions|) ==> (befores[(i + 1)] == step(befores[i], actions[i]))))
  ensures ((validateFrom(step, legal, s, befores, actions) == true) ==> forall i: int :: ((0 <= i) ==> (i < |actions|) ==> legal(befores[i], actions[i])))
  decreases |actions|
{
  // --- proof addition: induction; a validated episode chains from s (P2) and
  // is legal at every ply (P4). Chaining is the tamper-rejection teeth: a
  // forged before[i] breaks befores[i] == step(befores[i-1], ...), so !validate.
  if (|actions| == 0) {
  } else if (befores[0] != s) {
  } else if (!legal(s, actions[0])) {
  } else {
    validateFrom_ensures(step, legal, step(s, actions[0]), befores[1..], actions[1..]); // IH on the tail
    if (validateFrom(step, legal, s, befores, actions) == true) {
      assert validateFrom(step, legal, step(s, actions[0]), befores[1..], actions[1..]) == true;
      forall i | 0 <= i && (i + 1) < |actions|
        ensures befores[i + 1] == step(befores[i], actions[i])
      {
        if (i == 0) {
          assert befores[i + 1] == befores[1..][0];
        } else {
          assert befores[i + 1] == befores[1..][i];
          assert befores[i] == befores[1..][i - 1];
          assert actions[i] == actions[1..][i - 1];
        }
      }
      forall i | 0 <= i < |actions|
        ensures legal(befores[i], actions[i])
      {
        if (i == 0) {
        } else {
          assert befores[i] == befores[1..][i - 1];
          assert actions[i] == actions[1..][i - 1];
        }
      }
    }
  }
}

function genuinePlayValidates<S(==), A(==)>(step: (S, A) -> S, legal: (S, A) -> bool, s: S, befores: seq<S>, actions: seq<A>): bool
  requires (|befores| == |actions|)
  requires ((|actions| > 0) ==> (befores[0] == s))
  requires forall i: int :: ((0 <= i) ==> ((i + 1) < |actions|) ==> (befores[(i + 1)] == step(befores[i], actions[i])))
  requires forall i: int :: ((0 <= i) ==> (i < |actions|) ==> legal(befores[i], actions[i]))
  decreases |actions|
{
  validateFrom(step, legal, s, befores, actions)
}

lemma genuinePlayValidates_ensures<S, A>(step: (S, A) -> S, legal: (S, A) -> bool, s: S, befores: seq<S>, actions: seq<A>)
  requires (|befores| == |actions|)
  requires ((|actions| > 0) ==> (befores[0] == s))
  requires forall i: int :: ((0 <= i) ==> ((i + 1) < |actions|) ==> (befores[(i + 1)] == step(befores[i], actions[i])))
  requires forall i: int :: ((0 <= i) ==> (i < |actions|) ==> legal(befores[i], actions[i]))
  ensures (genuinePlayValidates(step, legal, s, befores, actions) == true)
  decreases |actions|
{
  // --- proof addition: a genuine (chained + legal) play always validates ---
  if (|actions| == 0) {
  } else {
    // The tail (befores[1..], actions[1..]) is itself a genuine play from step(s, a0).
    assert |actions| > 1 ==> befores[1] == step(befores[0], actions[0]); // chaining at i=0
    assert forall j: int :: (0 <= j ==> (j + 1) < |actions[1..]| ==> befores[1..][j + 1] == step(befores[1..][j], actions[1..][j])) by {
      forall j | 0 <= j && (j + 1) < |actions[1..]|
        ensures befores[1..][j + 1] == step(befores[1..][j], actions[1..][j])
      {
        assert befores[1..][j + 1] == befores[j + 2];
        assert befores[1..][j] == befores[j + 1];
        assert actions[1..][j] == actions[j + 1];
      }
    }
    assert forall j: int :: (0 <= j ==> j < |actions[1..]| ==> legal(befores[1..][j], actions[1..][j])) by {
      forall j | 0 <= j && j < |actions[1..]|
        ensures legal(befores[1..][j], actions[1..][j])
      {
        assert befores[1..][j] == befores[j + 1];
        assert actions[1..][j] == actions[j + 1];
      }
    }
    genuinePlayValidates_ensures(step, legal, step(s, actions[0]), befores[1..], actions[1..]); // IH
    assert validateFrom(step, legal, step(s, actions[0]), befores[1..], actions[1..]) == true;
  }
}
