// Generated by lsc from replay_core.ts

function statesFrom<S(==), A(==)>(step: (S, A) -> S, s: S, actions: seq<A>): seq<S>
  decreases |actions|
{
  if (|actions| == 0) then
    [s]
  else
    var rest := statesFrom(step, step(s, actions[0]), actions[1..]);
    ([s] + rest)
}

lemma statesFrom_ensures<S, A>(step: (S, A) -> S, s: S, actions: seq<A>)
  ensures (|statesFrom(step, s, actions)| == (|actions| + 1))
  ensures (statesFrom(step, s, actions)[0] == s)
  ensures forall i: int :: ((0 <= i) ==> (i < |actions|) ==> (statesFrom(step, s, actions)[(i + 1)] == step(statesFrom(step, s, actions)[i], actions[i])))
{
}

function validateFrom<S(==), A(==)>(step: (S, A) -> S, legal: (S, A) -> bool, s: S, befores: seq<S>, actions: seq<A>): bool
  decreases |actions|
{
  ((|actions| == 0) || (if (|befores| == 0) then false else (if (befores[0] != s) then false else (if !(legal(s, actions[0])) then false else validateFrom(step, legal, step(s, actions[0]), befores[1..], actions[1..])))))
}

lemma validateFrom_ensures<S, A>(step: (S, A) -> S, legal: (S, A) -> bool, s: S, befores: seq<S>, actions: seq<A>)
  ensures ((validateFrom(step, legal, s, befores, actions) == true) ==> (|actions| <= |befores|))
  ensures ((validateFrom(step, legal, s, befores, actions) == true) ==> (|actions| > 0) ==> ((|befores| > 0) && (befores[0] == s)))
  ensures ((validateFrom(step, legal, s, befores, actions) == true) ==> forall i: int :: ((0 <= i) ==> ((i + 1) < |actions|) ==> (((i + 1) < |befores|) && (befores[(i + 1)] == step(befores[i], actions[i])))))
  ensures ((validateFrom(step, legal, s, befores, actions) == true) ==> forall i: int :: ((0 <= i) ==> (i < |actions|) ==> ((i < |befores|) && legal(befores[i], actions[i]))))
{
}

function genuinePlayValidates<S(==), A(==)>(step: (S, A) -> S, legal: (S, A) -> bool, s: S, befores: seq<S>, actions: seq<A>): bool
  requires (|befores| == |actions|)
  requires ((|actions| > 0) ==> (befores[0] == s))
  requires forall i: int :: ((0 <= i) ==> ((i + 1) < |actions|) ==> (befores[(i + 1)] == step(befores[i], actions[i])))
  requires forall i: int :: ((0 <= i) ==> (i < |actions|) ==> legal(befores[i], actions[i]))
  decreases |actions|
{
  validateFrom(step, legal, s, befores, actions)
}

lemma genuinePlayValidates_ensures<S, A>(step: (S, A) -> S, legal: (S, A) -> bool, s: S, befores: seq<S>, actions: seq<A>)
  requires (|befores| == |actions|)
  requires ((|actions| > 0) ==> (befores[0] == s))
  requires forall i: int :: ((0 <= i) ==> ((i + 1) < |actions|) ==> (befores[(i + 1)] == step(befores[i], actions[i])))
  requires forall i: int :: ((0 <= i) ==> (i < |actions|) ==> legal(befores[i], actions[i]))
  ensures (genuinePlayValidates(step, legal, s, befores, actions) == true)
{
}

function recordBefores<S(==), A(==)>(step: (S, A) -> S, s: S, actions: seq<A>): seq<S>
  decreases |actions|
{
  if (|actions| == 0) then
    []
  else
    ([s] + recordBefores(step, step(s, actions[0]), actions[1..]))
}

lemma recordBefores_ensures<S, A>(step: (S, A) -> S, s: S, actions: seq<A>)
  ensures (|recordBefores(step, s, actions)| == |actions|)
{
}

function allLegalFrom<S(==), A(==)>(step: (S, A) -> S, legal: (S, A) -> bool, s: S, actions: seq<A>): bool
  decreases |actions|
{
  ((|actions| == 0) || (if !(legal(s, actions[0])) then false else allLegalFrom(step, legal, step(s, actions[0]), actions[1..])))
}

function recordedPlayValidates<S(==), A(==)>(step: (S, A) -> S, legal: (S, A) -> bool, s: S, actions: seq<A>): bool
  requires allLegalFrom(step, legal, s, actions)
{
  validateFrom(step, legal, s, recordBefores(step, s, actions), actions)
}

lemma recordedPlayValidates_ensures<S, A>(step: (S, A) -> S, legal: (S, A) -> bool, s: S, actions: seq<A>)
  requires allLegalFrom(step, legal, s, actions)
  ensures (recordedPlayValidates(step, legal, s, actions) == true)
{
}
